version: "3.7"

services:
  postgres:
    image: postgres:13.6
    container_name: restapi_postgres
    restart: always
    environment:
      POSTGRES_USER: restapi
      POSTGRES_PASSWORD: restapi
      POSTGRES_DB: restapi
    volumes:
      - $HOME/postgresql/restapi:/var/lib/postgresql/data
    ports:
      - "3000:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
